linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - fatcontext
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godox
    - inamedparam
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noctx
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - execinquery
    - gomnd
    - stylecheck
    - maintidx

linters-settings:
  gci:
    sections:
      - prefix(github.com/prometheus-community/windows_exporter/pkg/initiate)
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
    custom-order: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `upperSnake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`
        json: camel
        yaml: snake

issues:
  exclude:
  - don't use underscores in Go names
  - don't use an underscore in package name
  - exported type .+ should have comment or be unexported
  exclude-rules:
  - # Golint has many capitalisation complaints on WMI class names
    text: "`?\\w+`? should be `?\\w+`?"
    linters:
    - revive
  - text: "don't use ALL_CAPS in Go names; use CamelCase"
    linters:
    - revive
