linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - gocyclo
    - gomoddirectives
    - gomodguard
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - execinquery
    - gomnd

issues:
  exclude:
  - don't use underscores in Go names
  - don't use an underscore in package name
  - exported type .+ should have comment or be unexported
  exclude-rules:
  - # Golint has many capitalisation complaints on WMI class names
    text: "`?\\w+`? should be `?\\w+`?"
    linters:
    - revive
  - text: "don't use ALL_CAPS in Go names; use CamelCase"
    linters:
    - revive
