linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - revive
  - govet
  - gofmt
  - ineffassign
  - unconvert
  - varcheck

issues:
  exclude:
  - don't use underscores in Go names
  - don't use an underscore in package name
  - exported type .+ should have comment or be unexported
  exclude-rules:
  - # Golint has many capitalisation complaints on WMI class names
    text: "`?\\w+`? should be `?\\w+`?"
    linters:
    - revive
  - text: "don't use ALL_CAPS in Go names; use CamelCase"
    linters:
    - revive
