go:
  # Whenever the Go version is updated here,
  # .github/workflows should also be updated.
  version: 1.23
  cgo: false
repository:
  path: github.com/prometheus-community/windows_exporter
build:
  binaries:
    - name: windows_exporter
      path: ./cmd/windows_exporter
  tags:
    all:
      - trimpath
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
crossbuild:
  platforms:
    - windows/amd64
    - windows/arm64
