(import '../mixin.libsonnet') {
  _config+:: {
    windowsExporterSelector: 'job=~"windows.*", cluster="test"',
    volumeSelector: 'volume!~"HarddiskVolume.*"',
    nicSelector: 'nic!="Loopback"',
    rateInterval: '2m',
    cpuHighUsageThreshold: 80,
    memoryHighUsageThreshold: 85,
    diskFreeWarningThreshold: 20,
    diskFreeCriticalThreshold: 10,
    criticalSeverity: 'page',
    enableActiveDirectory: true,
    enableTime: true,
    runbookURLPattern: 'https://runbooks.example.com/windows/%s/',
    memoryCommitHighUsageThreshold: 80,
    diskLatencyThresholdSeconds: 0.02,
    networkErrorRateThreshold: 0.5,
    networkDiscardRateThreshold: 0.5,
    clockOffsetThresholdSeconds: 0.1,
    adPendingReplicationThreshold: 10,
    adReplicationFailureRateThreshold: 0.5,
  },
}
