name: 🐞 Bug
description: Something is not working as indended.
labels: [ 🐞 bug ]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  
  - type: markdown
    attributes:
      value: |-
        > [!NOTE]
        > If you encounter "Counter not found" issues, try to re-build  the performance counter first.

        ```
        PS C:\WINDOWS\system32> cd c:\windows\system32
        PS C:\windows\system32> lodctr /R
        
        Error: Unable to rebuild performance counter setting from system backup store, error code is 2
        PS C:\windows\system32> cd ..
        PS C:\windows> cd syswow64
        PS C:\windows\syswow64> lodctr /R
        
        Info: Successfully rebuilt performance counter setting from system backup store
        PS C:\windows\syswow64> winmgmt.exe /RESYNCPERF
        ```
        
        ----
  
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: |
        When I do <X>, <Y> happens and I see the error message attached below:
        ```...```
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: When I do <X>, <Z> should happen instead.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: Markdown
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - **windows_exporter Version**: 0.26
        - **Windows Server Version**: 2019
      value: |
        - windows_exporter Version:
        - Windows Server Version:
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: windows_exporter logs
      description: |
        Log of windows_exporter.
        ⚠️ Without proving logs, we unable to assist here. ⚠️
      render: shell
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
