name: ❓ Question
description: Something is not clear.
labels: [ ❓ question ]
body:
  
  - type: markdown
    attributes:
      value: |-
        > [!NOTE]
        > If you encounter "Counter not found" issues, try to re-build  the performance counter first.

        ```
        PS C:\WINDOWS\system32> cd c:\windows\system32
        PS C:\windows\system32> lodctr /R
        
        Error: Unable to rebuild performance counter setting from system backup store, error code is 2
        PS C:\windows\system32> cd ..
        PS C:\windows> cd syswow64
        PS C:\windows\syswow64> lodctr /R
        
        Info: Successfully rebuilt performance counter setting from system backup store
        PS C:\windows\syswow64> winmgmt.exe /RESYNCPERF
        ```
        
        ----

  - type: textarea
    attributes:
      label: Problem Statement
      description: Without specifying a solution, describe what the project is missing today.
      placeholder: |
        The rotating project logo has a fixed size and color.
        There is no way to make it larger and more shiny.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - **windows_exporter Version**: 0.26
        - **Windows Server Version**: 2019
      value: |
        - windows_exporter Version:
        - Windows Server Version:
    validations:
      required: true

