name: Spell checking

# Trigger on pull requests, and pushes to master branch.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  VERSION_PROMU: 'v0.14.0'

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: codespell-project/actions-codespell@3c04c03694eb927ff908b8b5abfe9c58b239b0ae # master
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          skip: ./.git,go.mod,go.sum
          ignore_words_list: calle,Entires
