package smtp

const (
	BadmailedMessagesBadPickupFileTotal     = "Badmailed Messages (Bad Pickup File)"
	BadmailedMessagesGeneralFailureTotal    = "Badmailed Messages (General Failure)"
	BadmailedMessagesHopCountExceededTotal  = "Badmailed Messages (Hop Count Exceeded)"
	BadmailedMessagesNDROfDSNTotal          = "Badmailed Messages (NDR of DSN)"
	BadmailedMessagesNoRecipientsTotal      = "Badmailed Messages (No Recipients)"
	BadmailedMessagesTriggeredViaEventTotal = "Badmailed Messages (Triggered via Event)"
	BytesSentTotal                          = "Bytes Sent Total"
	BytesReceivedTotal                      = "Bytes Received Total"
	CategorizerQueueLength                  = "Categorizer Queue Length"
	ConnectionErrorsTotal                   = "Total Connection Errors"
	CurrentMessagesInLocalDelivery          = "Current Messages in Local Delivery"
	DirectoryDropsTotal                     = "Directory Drops Total"
	DNSQueriesTotal                         = "DNS Queries Total"
	DSNFailuresTotal                        = "Total DSN Failures"
	ETRNMessagesTotal                       = "ETRN Messages Total"
	InboundConnectionsCurrent               = "Inbound Connections Current"
	InboundConnectionsTotal                 = "Inbound Connections Total"
	LocalQueueLength                        = "Local Queue Length"
	LocalRetryQueueLength                   = "Local Retry Queue Length"
	MailFilesOpen                           = "Number of MailFiles Open"
	MessageBytesReceivedTotal               = "Message Bytes Received Total"
	MessageBytesSentTotal                   = "Message Bytes Sent Total"
	MessageDeliveryRetriesTotal             = "Message Delivery Retries"
	MessageSendRetriesTotal                 = "Message Send Retries"
	MessagesCurrentlyUndeliverable          = "Messages Currently Undeliverable"
	MessagesDeliveredTotal                  = "Messages Delivered Total"
	MessagesPendingRouting                  = "Messages Pending Routing"
	MessagesReceivedTotal                   = "Messages Received Total"
	MessagesRefusedForAddressObjectsTotal   = "Messages Refused for Address Objects"
	MessagesRefusedForMailObjectsTotal      = "Messages Refused for Mail Objects"
	MessagesRefusedForSizeTotal             = "Messages Refused for Size"
	MessagesSentTotal                       = "Messages Sent Total"
	MessagesSubmittedTotal                  = "Total messages submitted"
	NDRsGeneratedTotal                      = "NDRs Generated"
	OutboundConnectionsCurrent              = "Outbound Connections Current"
	OutboundConnectionsRefusedTotal         = "Outbound Connections Refused"
	OutboundConnectionsTotal                = "Outbound Connections Total"
	QueueFilesOpen                          = "Number of QueueFiles Open"
	PickupDirectoryMessagesRetrievedTotal   = "Pickup Directory Messages Retrieved Total"
	RemoteQueueLength                       = "Remote Queue Length"
	RemoteRetryQueueLength                  = "Remote Retry Queue Length"
	RoutingTableLookupsTotal                = "Routing Table Lookups Total"
)
